complete table
peaksoft-school/peaksoftlms-js8 pull request #14
Opened 2023-04-07 08:38 UTC by ZarinaOrgubaeva

2023-04-07 09:15 UTC, kalmatovski commented
pagination?

2023-04-07 10:25 UTC, songhee24 requested changes

2023-04-07 10:25 UTC, songhee24 commented on src/components/UI/Table.jsx
> +      <TableContainerStyled component={Paper}>
<img width="1350" alt="Screenshot 2023-03-29 at 16 15 46" src="https://user-images.githubusercontent.com/44497623/230592602-ff4f7e26-180b-45f1-9440-4c0e44242077.png">
посмотрите на дизайн там мягкие цвета 

<img width="794" alt="Screenshot 2023-03-29 at 16 22 37" src="https://user-images.githubusercontent.com/44497623/230592643-2125a6ff-b17a-40a6-ae86-a2bec1029301.png">

плюс не делайте фиксированным
<img width="1394" alt="Screenshot 2023-03-29 at 16 23 21" src="https://user-images.githubusercontent.com/44497623/230592747-9d7aa856-86d8-4508-92ab-7b1fb8881e58.png">

2023-04-07 10:25 UTC, songhee24 commented on src/components/UI/Table.jsx
> +   const columns = [
выпишите это все в константы и плюс создайте все возможные константы для всех видов таблиц

2023-04-07 12:11 UTC, songhee24 requested changes

2023-04-07 12:11 UTC, songhee24 commented on src/utlis/constants/Table.jsx
> +         <Table sx={{ minWidth: 650 }} aria-label="simple table">
sx={{ minWidth: 650 }} width не стоит делать фиксированным

2023-04-07 12:11 UTC, songhee24 commented on src/utlis/constants/Table.jsx
> +                  {columns.map((column) => (
columns, rows нужна проверка на columns, rows вдруг они будут null

2023-04-08 17:15 UTC, songhee24 requested changes

2023-04-08 17:15 UTC, songhee24 commented on src/utlis/constants/Table.jsx
> +   margin-top: 5.25rem;
чаще всего верстка должна быть однонаправленной те кто вызывает компоненту ему какие то внешние маржины могут мешать он должен сам задавать если ему нужно

2023-04-08 17:15 UTC, songhee24 commented on src/utlis/constants/Table.jsx
> +   margin-left: 1.25rem;
тоже самое здесь

2023-04-11 08:30 UTC, songhee24 approved these changes

2023-04-11 08:30 UTC, merged