Feature/meatballs
peaksoft-school/peaksoftlms-js8 pull request #15
Opened 2023-04-07 09:50 UTC by abdirasulovna

2023-04-07 10:00 UTC, kalmatovski commented
чуть сложновато, но думаю справимся

2023-04-07 10:31 UTC, songhee24 requested changes

2023-04-07 10:31 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +            <MenuItem onClick={onClose}>
<img width="287" alt="Screenshot 2023-03-29 at 16 28 42" src="https://user-images.githubusercontent.com/44497623/230593599-400dba9b-f1d5-4270-9ead-6ff6099bcdb7.png">
differences
<img width="419" alt="Screenshot 2023-03-29 at 16 29 46" src="https://user-images.githubusercontent.com/44497623/230593623-b4eae437-53c0-40ae-a48b-b9852f529779.png">

2023-04-07 10:31 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +               <EditIcon />
и да нужно чтобы значения MenuItem все приходили извне

2023-04-08 14:11 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +            onClick={onClick}
onClick={onClick} ?

2023-04-08 14:13 UTC, songhee24 requested changes

2023-04-08 14:13 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +               <StyledMenuItem onClick={onClose}>
как мне получить item который он выберет ?

2023-04-08 14:13 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +                  {item.icon}
не хватает key prop

2023-04-08 14:15 UTC, songhee24 requested changes

2023-04-08 14:15 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +            {arrayIcon.map((item) => (
поставь еще проверку на null и так лучше чтобы arrayIcon тоже приходил через пропсы

2023-04-08 17:31 UTC, songhee24 requested changes

2023-04-08 17:31 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +   const [anchorEl, setAnchorEl] = useState(null)
![Screenshot 2023-03-30 at 23 30 30](https://user-images.githubusercontent.com/44497623/230734980-ffa1cec0-7506-49cb-ba50-08d67b682158.png)
все это должны приходить через пропсы вы создаете controlled component

2023-04-08 17:31 UTC, songhee24 commented on src/components/UI/Meatballs.jsx
> +            onClose={handleClose}
и да вы все равно не выбираете элемент по которому вы нажали

2023-04-08 21:42 UTC, songhee24 approved these changes

2023-04-08 21:42 UTC, merged