tabs
peaksoft-school/peaksoftlms-js8 pull request #17
Opened 2023-04-10 08:10 UTC by abdirasulovna

2023-04-10 09:01 UTC, kalmatovski commented
может по ролям будет контент меняться?

2023-04-11 10:50 UTC, songhee24 requested changes

2023-04-11 10:50 UTC, songhee24 commented on src/components/UI/Tabs.jsx
> +      <Container>
таб когда меняется он должен менять контент который под ним находится 
так как он будет определять какой контент вы выбрали ?

2023-04-12 07:43 UTC, songhee24 approved these changes

2023-04-12 07:43 UTC, songhee24 commented on src/components/UI/Tabs.jsx
> +               <StyledLink to="/">Учителя</StyledLink>
Давайте сделаем так чтобы табы работали как conditional rendering не List

2023-04-12 07:43 UTC, merged