select
peaksoft-school/peaksoftlms-js8 pull request #19
Opened 2023-04-10 09:51 UTC by mirlnovna

2023-04-10 10:31 UTC, kalmatovski commented
все четко думаю, ждем комментарии агая

2023-04-11 11:03 UTC, songhee24 requested changes

2023-04-11 11:03 UTC, songhee24 commented on src/components/UI/Select.jsx
> +      <div>
зачем div

2023-04-11 11:03 UTC, songhee24 commented on src/components/UI/Select.jsx
> +const MultiSelect = ({ value, onChange }) => {
...rest

2023-04-11 11:03 UTC, songhee24 commented on src/components/UI/Select.jsx
> +const names = [
должно передаваться через props

2023-04-11 11:03 UTC, songhee24 commented on src/components/UI/Select.jsx
> +               renderValue={(selected) => selected.join(', ')}
когда multiple select нужно работать с объектом данных а не с строками

2023-04-11 11:03 UTC, songhee24 commented on src/components/UI/Select.jsx
> +               renderValue={(selected) => selected.join(', ')}
потому что вы будете давать id выбранных объектов а не их имена

2023-04-11 11:49 UTC, songhee24 requested changes

2023-04-11 11:49 UTC, songhee24 commented on src/components/UI/Select.jsx
> +      <FormControl sx={{ m: 1, width: 300 }}>
width: 300 не нужен

2023-04-11 11:49 UTC, songhee24 commented on src/components/UI/Select.jsx
> +               <MenuItem key={item.name} value={item.name}>
value={item.name} а если мне нужно будет не по name а по item.id выбирать ?

2023-04-11 12:11 UTC, mirlnovna commented on src/components/UI/Select.jsx
> +               <MenuItem key={item.name} value={item.name}>
агай ошондо условия тузуш керекпи?

2023-04-11 12:12 UTC, songhee24 commented on src/components/UI/Select.jsx
> +               <MenuItem key={item.name} value={item.name}>
жок азырынча item.id бериш керек

2023-04-11 12:16 UTC, songhee24 approved these changes

2023-04-11 12:16 UTC, merged