Feature/avatar
peaksoft-school/peaksoftlms-js8 pull request #20
Opened 2023-04-10 10:05 UTC by Ominakhan

2023-04-10 10:31 UTC, kalmatovski commented
все четко думаю, ждем комментарии агая

2023-04-11 11:05 UTC, songhee24 approved these changes

2023-04-11 11:11 UTC, songhee24 requested changes

2023-04-11 11:11 UTC, songhee24 commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
вы должны были сделать так чтобы любой мог использовать вашу логику  handleAvatarChange

2023-04-11 11:11 UTC, songhee24 commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
чтобы мог вызвать в любом компонента и применить загрузки аватарки

2023-04-11 14:23 UTC, Ominakhan commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
ya ne ponyala, v moem sluchae toje vrode mojno vyzyvat' componenta i lyuboi mojet polzovatsya

2023-04-11 15:09 UTC, songhee24 commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
Нет вы сделали reusable component 
Да это хорошо и нормальная практика 
Нужно чтобы любой мог пользоваться не КОМПОНЕНТОМ а функцией позволяющим выбирать фотография 
Потому что я могу загружать фотку не только аватарку а любая другая ситуация возможна

2023-04-11 15:19 UTC, Ominakhan commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
Customnyi hook sozdat'  avatara?

2023-04-11 15:20 UTC, Ominakhan commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
ili redux?

2023-04-11 15:25 UTC, songhee24 commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
Кастомный хук мне кажется будет отличным вариантом как раз на вашей компоненте сделаете тест

2023-04-11 16:43 UTC, Ominakhan commented on src/components/UI/Avatar.jsx
> +   const handleAvatarChange = (event) => {
sozdala Customniy hook, teper' udalit' componenta ili ostavit'? Protestirovala na componente, vse rabotaet

2023-04-12 08:07 UTC, songhee24 approved these changes

2023-04-12 08:15 UTC, merged