AddModal
peaksoft-school/peaksoftlms-js8 pull request #25
Opened 2023-04-14 09:00 UTC by ZarinaOrgubaeva

2023-04-14 09:07 UTC, Ominakhan commented on package-lock.json
not comments

2023-04-17 09:18 UTC, songhee24 requested changes

2023-04-17 09:18 UTC, songhee24 commented on src/components/addModal/ModalInstructor.jsx
> +import PhoneInput from 'react-phone-input-2'
<img width="559" alt="Screenshot 2023-04-17 at 15 11 48" src="https://user-images.githubusercontent.com/44497623/232439716-b0dba73c-f8ed-4def-8437-81ef45bae088.png">
why the file name and component name are different ?

2023-04-17 09:18 UTC, songhee24 commented on src/components/addModal/ModalInstructor.jsx
> +                  country="kg"
<img width="365" alt="Screenshot 2023-04-17 at 15 14 40" src="https://user-images.githubusercontent.com/44497623/232440534-054bc997-de7e-4649-a2a2-ffa3ce1b679c.png">
it's good to use outside packages for solve problem but which problem did that solve  ?

2023-04-17 09:18 UTC, songhee24 commented on src/components/addModal/ModalInstructor.jsx
> +                  country="kg"
our application only SNG users only

2023-04-17 09:18 UTC, songhee24 commented on src/components/addModal/ModalInstructor.jsx
> +                  type="email"
<img width="238" alt="Screenshot 2023-04-17 at 15 17 37" src="https://user-images.githubusercontent.com/44497623/232441344-574e4744-f3fc-40df-9060-4ee1ce7ee997.png">
border bloated

2023-04-17 09:54 UTC, ZarinaOrgubaeva commented on src/components/addModal/ModalInstructor.jsx
> +                  country="kg"
А вы России не пользуется? Я слышала что есть студент учащиеся оnline в Tурции и т.д.

2023-04-17 10:02 UTC, ZarinaOrgubaeva commented on src/components/addModal/ModalInstructor.jsx
> +import PhoneInput from 'react-phone-input-2'
потому что addModalInstructor в имени файл не уместилось а к тому же имя папка  addModal думала этого достаточно

2023-04-17 11:15 UTC, songhee24 commented on src/components/addModal/ModalInstructor.jsx
> +import PhoneInput from 'react-phone-input-2'
нет проблема не в этом а в том что стоит называть компоненту так же как вы навали файл

2023-04-17 11:16 UTC, songhee24 commented on src/components/addModal/ModalInstructor.jsx
> +                  country="kg"
yes, it is, but in the demo project there is no multi-language, it turns out only sng

2023-04-18 08:53 UTC, songhee24 approved these changes

2023-05-01 11:02 UTC, merged