textare
peaksoft-school/peaksoftlms-js8 pull request #26
Opened 2023-04-14 12:56 UTC by mirlnovna

2023-04-14 13:14 UTC, kalmatovski commented
очистите корневой файл пожалуйста, а так с кодом вроде бы проблем нет

2023-04-17 09:06 UTC, songhee24 requested changes

2023-04-17 09:06 UTC, songhee24 commented on src/components/UI/TextArea.jsx
> +const TextArea = ({ value, onChange, ...rest }) => {
also need to provide ref

2023-04-17 09:06 UTC, songhee24 commented on src/components/UI/TextArea.jsx
> +   width: '491px',
fixed width need to remove

2023-04-17 11:17 UTC, songhee24 approved these changes

2023-04-17 11:17 UTC, merged