Feature/snack bar
peaksoft-school/peaksoftlms-js8 pull request #27
Opened 2023-04-16 04:42 UTC by kalmatovski

2023-04-16 15:51 UTC, ZarinaOrgubaeva commented
good job!

2023-04-17 09:05 UTC, songhee24 requested changes

2023-04-17 09:05 UTC, songhee24 commented on src/components/UI/Snackbar.jsx
> +export const Snackbar = ({ type = 'success', message, text }) => {
снакбар должен работать так чтобы его могли вызывать как функцию а не как компоненту

2023-04-17 09:05 UTC, songhee24 commented on src/components/UI/Snackbar.jsx
> +export const Snackbar = ({ type = 'success', message, text }) => {
то есть без кнопки 
`  <Button type="submit" onClick={notify}>
            {text}
         </Button>`

2023-04-17 09:05 UTC, songhee24 commented on src/components/UI/Snackbar.jsx
> +export const Snackbar = ({ type = 'success', message, text }) => {
по другому я могу вызвать метод notify() внутри допустим любой другой функции

2023-04-18 08:54 UTC, songhee24 approved these changes

2023-04-19 06:11 UTC, merged