Feature/select input
peaksoft-school/peaksoftlms-js8 pull request #28
Opened 2023-04-17 05:06 UTC by abdirasulovna

2023-04-17 05:16 UTC, kalmatovski commented
good job, u r amazing:)

2023-04-17 12:03 UTC, songhee24 requested changes

2023-04-17 12:03 UTC, songhee24 commented on src/components/UI/CardLesson.jsx
> +         {lessonTitle.map((item) => (
это тоже пропс

2023-04-17 12:03 UTC, songhee24 commented on src/components/UI/CardLesson.jsx
> +            <StyledSelect value="">{title}</StyledSelect>
почему и тут тоже title

2023-04-18 08:59 UTC, songhee24 requested changes

2023-04-18 08:59 UTC, songhee24 commented on src/components/UI/SelectInput.jsx
> +const SelectInput = ({ onChange, onClick, value, ...restProps }) => {
onChange, onClick, зачем вам две функции ?

2023-04-18 09:43 UTC, songhee24 approved these changes

2023-04-18 09:43 UTC, merged