Feature/sign in layout
peaksoft-school/peaksoftlms-js8 pull request #29
Opened 2023-04-17 09:50 UTC by Ominakhan

2023-04-17 09:58 UTC, kalmatovski commented
greate верстка ::)

2023-04-18 09:35 UTC, songhee24 requested changes

2023-04-18 09:35 UTC, songhee24 commented on src/containers/CreatePassword.jsx
> +const CreatePassword = () => {
CreatePassword должно быть формой плюс должна быть логика подъема состояния

2023-04-18 09:35 UTC, songhee24 commented on src/containers/CreatePassword.jsx
> +                     <Password
плюс нужна логика проверок пароля

2023-04-18 09:35 UTC, songhee24 commented on src/containers/ForgotPassword.jsx
почему папка containers это же модалка обычная ?
<img width="531" alt="Screenshot 2023-04-18 at 15 31 01" src="https://user-images.githubusercontent.com/44497623/232735147-2e054168-5172-4666-974c-602b844d3dd9.png">

2023-04-18 09:35 UTC, songhee24 commented on src/containers/ForgotPassword.jsx
> +               <InputStyle placeholder="Введите ваш Email" />
нужна валидация почты

2023-04-18 09:35 UTC, songhee24 commented on src/containers/SignIn.jsx
> +      <GridContainerStyle container>
компонента в которой 2 или больше инпутов должна быть формой

2023-04-18 09:57 UTC, Ominakhan commented on src/containers/SignIn.jsx
> +      <GridContainerStyle container>
Eto ne forma?
<Box component="form" type="submit">
                  <Box>
                     <Password
                        title="Новый пароль:"
                        placeholder="Введите новый пароль"
                     />
                  </Box>
                  <Box>
                     <Password
                        title="Подтверждение:"
                        placeholder="Подтвердите пароль"
                     />
                  </Box>

                  <Box>
                     <ButtonStyle>Создать</ButtonStyle>
                  </Box>
               </Box>

2023-04-18 10:02 UTC, Ominakhan commented on src/containers/SignIn.jsx
> +      <GridContainerStyle container>
Eto ne forma ? <Box component = "form" type = "submit>  iz MUI vzyala

2023-04-18 10:04 UTC, songhee24 requested changes

2023-04-18 10:04 UTC, songhee24 commented on src/containers/SignIn.jsx
> +      <GridContainerStyle container>
да форма но если вы component = "form" type = "submit не напишите она не будет формой

2023-04-18 13:38 UTC, Ominakhan commented on src/containers/CreatePassword.jsx
> +const CreatePassword = () => {
zdes' ne ponyala,  logika emaila i passworda?

2023-04-18 13:39 UTC, Ominakhan commented on src/containers/ForgotPassword.jsx
> +               <InputStyle placeholder="Введите ваш Email" />
mojno li dlya validatsii polzovat'sya hook useForm?

2023-04-18 13:41 UTC, songhee24 commented on src/containers/CreatePassword.jsx
> +const CreatePassword = () => {
Будет хорошо если воспользоваться библиотекой

2023-04-18 13:42 UTC, songhee24 commented on src/containers/ForgotPassword.jsx
> +               <InputStyle placeholder="Введите ваш Email" />
Будет хорошо если воспользоваться библиотекой

2023-04-18 13:43 UTC, songhee24 commented on src/containers/CreatePassword.jsx
> +const CreatePassword = () => {
Да в большинстве случаев форма собирает данные и передаёт компоненте которая ее вызывает

2023-04-26 08:17 UTC, songhee24 approved these changes

2023-04-26 08:18 UTC, merged