configure store
peaksoft-school/peaksoftlms-js8 pull request #33
Opened 2023-04-26 07:20 UTC by abdirasulovna

2023-04-26 07:26 UTC, mirlnovna commented
Вроде все правильно, ждем ответа

2023-04-26 07:27 UTC, Ominakhan commented on src/redux/store/index.js
> +})
oshibku ne nashla

2023-04-26 07:50 UTC, kalmatovski commented
а как на счет email, password и главного состояния isAuthorized?

2023-04-27 12:19 UTC, songhee24 requested changes

2023-04-27 12:19 UTC, songhee24 commented on src/redux/reducers/user/userSlice.js
> +   password: '',
password лишнее

2023-04-27 12:19 UTC, songhee24 commented on src/redux/reducers/user/userSlice.js
> +   email: '',
email тоже

2023-04-28 05:06 UTC, songhee24 approved these changes

2023-04-28 05:31 UTC, merged