signin
peaksoft-school/peaksoftlms-js8 pull request #35
Opened 2023-05-24 05:01 UTC by kalmatovski

2023-05-24 07:09 UTC, ZarinaOrgubaeva commented
good job!)

2023-05-24 09:54 UTC, Ominakhan commented on src/utlis/helpers/storageHelper.js
> +}
Jakshy kod

2023-05-29 10:10 UTC, songhee24 requested changes

2023-05-29 10:10 UTC, songhee24 commented on src/routes/ProtectedRoute.jsx
> +         role === USER_ROLES.ADMIN
да я говорил что нужно делать автоматом навигейт но зачем так усложнена ты можешь первести хотя бы в switch case

2023-05-29 10:10 UTC, songhee24 commented on src/routes/Routes.jsx
> +                     fallBackPath="."
fallBackPath="." lля чего она ? такого пропса даже нет

2023-05-29 10:10 UTC, songhee24 commented on src/App.js
> +         dispatch(authActions.autoLogin(loggedUser))
если ты хотел использовать мой метод настройки авто логина почему не сделал как я ? у тебя нету первоначального лоадинга нужно подождать пока данные из local storage вытаскиваются

2023-05-29 10:10 UTC, songhee24 commented on src/config/axiosInstance.js
>           headers: {
токен после перезагрузки страницы пропадет и больше не будет возможности отправлять запрос на защищенный ресурс

2023-05-29 11:02 UTC, songhee24 requested changes

2023-05-29 11:02 UTC, songhee24 commented on src/config/axiosInstance.js
> +            Authorization: store.getState().auth.accessToken,
Authorization: "Bearer и здесь нужно добавлять токен"

2023-05-29 11:13 UTC, songhee24 requested changes

2023-05-29 11:13 UTC, songhee24 commented on src/config/axiosInstance.js
> +            Authorization: `Bearer ${store.getState().auth.accessToken}`,
нужно еще проверить токен а потом давать ключ Authorization

2023-05-29 12:10 UTC, merged